jobs:
  include:
    - stage: node
      language: node_js
      node_js:
      - "node"
      - "6"
      - "4"
    - stage: docker
      sudo: required
      services:
        - docker
      script:
        - docker build --tag markdown-link-check .
        - docker run markdown-link-check
