#!/usr/bin/env node

'use strict';

var chalk = require('chalk');
var fs = require('fs');
var markdownLinkCheck = require('./');
var program = require('commander');
var request = require('request');
var url = require('url');
var path = require('path');

var statusLabels = {
    alive: chalk.green('✓'),
    dead: chalk.red('✖'),
    ignored: chalk.gray('/')
};

var error = false;
var opts = {};
var filenameForOutput = '';
var stream = process.stdin; // read from stdin unless a filename is given

program
    .option('-p, --progress', 'show progress bar')
    .option('-c, --config [config]', 'apply a config file (JSON), holding e.g. url specific header configuration')
    .option('-q, --quiet', 'displays errors only')
    .arguments('[filenameOrUrl]')
    .action(function (filenameOrUrl) {
    filenameForOutput = filenameOrUrl;
    if (/https?:/.test(filenameOrUrl)) {
        stream = request.get(filenameOrUrl);
        try { // extract baseUrl from supplied URL
            var parsed = url.parse(filenameOrUrl);
            delete parsed.search;
            delete parsed.hash;
            if (parsed.pathname.lastIndexOf('/') !== -1) {
                parsed.pathname = parsed.pathname.substr(0, parsed.pathname.lastIndexOf('/') + 1);
            }
            opts.baseUrl = url.format(parsed);
        } catch (err) { /* ignore error */ }
    } else {
        opts.baseUrl = 'file://' + path.dirname(path.resolve(filenameOrUrl));
        stream = fs.createReadStream(filenameOrUrl);
    }
}).parse(process.argv);

opts.showProgressBar = (program.progress === true); // force true or undefined to be true or false.
opts.quiet = (program.quiet === true);

var markdown = ''; // collect the markdown data, then process it
stream.on('data', function (chunk) {
    markdown += chunk.toString();
}).on('end', function () {
    if (filenameForOutput) {
        console.log(chalk.cyan('\nFILE: ' + filenameForOutput));
    }

    if (program.config) {
        fs.access(program.config, fs.constants.R_OK, function (err) {
            if (!err) {
                let configStream = fs.createReadStream(program.config);
                let configData = '';
                
                configStream.on('data', function (chunk) {
                    configData += chunk.toString();
                }).on('end', function () {
                    let config = JSON.parse(configData);

                    opts.ignorePatterns = config.ignorePatterns;
                    opts.httpHeaders = config.httpHeaders;
    
                    runMarkdownLinkCheck(markdown, opts);
                });
            }
            else {
                console.error(chalk.red('\nERROR: Config file not accessible.'));
                process.exit(1);
            }
        });
    }
    else {
        runMarkdownLinkCheck(markdown, opts);
    }
});

function runMarkdownLinkCheck(markdown, opts) {
    markdownLinkCheck(markdown, opts, function (err, results) {
        if (results.length === 0){
            console.log(chalk.yellow('No hyperlinks found!'));
        }
        results.forEach(function (result) {
            if(result.status === 'dead') {
                error = true;
            }

            // Skip messages for non-deadlinks in quiet mode.
            if (opts.quiet && result.status !== 'dead') {
                return;
            }

            console.log('[%s] %s', statusLabels[result.status], result.link);
        });
        if(error) {
            console.error(chalk.red('\nERROR: dead links found!'));
            process.exit(1);
        }
    });
}
